---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart systemd-logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Restart TLP
  ansible.builtin.service:
    name: tlp
    state: restarted
  listen: Restart TLP

- name: Reload Nagios on VM133
  ansible.builtin.service:
    name: nagios
    state: reloaded
  delegate_to: "{{ config.services.vms.nagios.ip }}"
  become: true
