- name: Configure Proxmox guest access
  hosts: proxmox_hosts
  become: true
  gather_facts: false
  vars:
    config: "{{ lookup('file', playbook_dir ~ '/../../config/homelab.yaml') | from_yaml }}"
  roles:
    - proxmox-haos
    - proxmox-container-ssh
    - proxmox-lxc-tun
    - proxmox-media-vm
