- name: Set Browser paths
  ansible.builtin.set_fact:
    browser_compose_dir: "/docker/docker-compose-{{ inventory_hostname }}"

- name: Create Browser application directory
  ansible.builtin.file:
    path: "{{ browser_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Browser config directory
  ansible.builtin.file:
    path: "{{ browser_compose_dir }}/config"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Copy Browser Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ browser_compose_dir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Deploy Browser via Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
  args:
    chdir: "{{ browser_compose_dir }}"
  changed_when: false
