- name: Set Healthchecks paths
  ansible.builtin.set_fact:
    healthchecks_compose_dir: "/docker/docker-compose-{{ inventory_hostname }}"

- name: Create Healthchecks application directory
  ansible.builtin.file:
    path: "{{ healthchecks_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Healthchecks data directory
  ansible.builtin.file:
    path: "{{ healthchecks_compose_dir }}/data"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Copy Healthchecks Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ healthchecks_compose_dir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0644'

- name: Deploy Healthchecks via Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
  args:
    chdir: "{{ healthchecks_compose_dir }}"
  changed_when: false
