docker-hosts:
  hosts:
    servarr:
      ansible_host: 10.20.30.100
      ansible_ssh_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

    nginx-proxy-manager:
      ansible_host: 10.20.30.101
      ansible_ssh_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

proxmox-hosts:
  hosts:
    proxmox:
      ansible_host: 10.20.30.155
      ansible_ssh_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

servarr-hosts:
  hosts:
    servarr:
      ansible_host: 10.20.30.100
      ansible_ssh_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

nginx-proxy-manager-hosts:
  hosts:
    servarr:
      ansible_host: 10.20.30.101
      ansible_ssh_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
