- name: Setup Proxmox server
  hosts: proxmox
  gather_facts: true
  become: true
  vars_files:
    - secrets.yml
  roles:
    - sys-monitoring
    # # - ups-monitor
    # - proxmox-terraform-setup
    # - power-saving
    - misc-utils
    - container-dirs

- name: Setup docker hosts
  hosts: docker-hosts
  gather_facts: true
  become: true
  roles:
    - docker
    - sys-monitoring
    - misc-utils
    - users # Needs run after container-dirs

- name: Setup servarr
  hosts: servarr-hosts
  gather_facts: true
  become: true
  roles:
    - servarr

- name: Setup nginx-proxy-manager
  hosts: nginx-proxy-manager-hosts
  gather_facts: true
  become: true
  roles:
    - nginx-proxy-manager
