---
- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Vacuum journal
  ansible.builtin.command:
    cmd: journalctl --vacuum-size={{ effective_log_policy.journald.system_max_use }}
  changed_when: false
