---
- name: Ensure terraform-prov user exists
  ansible.builtin.command: >
    pveum user add terraform-prov@pve --password "{{ terraform_user_password }}"
  register: user_result
  failed_when: "'already exists' not in user_result.stderr and user_result.rc != 0"
  changed_when: "'already exists' not in user_result.stderr"

- name: Ensure role assignment for terraform-prov
  ansible.builtin.command: >
    pveum aclmod / -user terraform-prov@pve -role Administrator
